name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Node Dependencies
        run: pnpm install
      - name: Check with prettier
        run: pnpm run lint:prettier

  eslint:
    runs-on: ubuntu-latest
    permissions:
      check: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Node Dependencies
        run: pnpm install
      - name: Save Code Linting Report JSON
        run: pnpm run lint:eslint --output-file eslint_report.json --format json
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        if: ${{ github.actor != 'dependabot[bot]' }} # dependabot doesn't have permissions
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'

  sveltecheck:
    runs-on: ubuntu-latest
    permissions:
      check: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Node Dependencies
        run: pnpm install
      - name: run svelte check
        run: pnpm run check
